.gitignore, Dockerfile, README.rst, docker-compose.yml, docs/source/installation.rst, setup.py
Out of the box the `cookiecutter bird` creates a `Dockerfile` that uses `conda`. It has been updated to use `pip` instead.  Issue #4 called to remove any `conda` items, but I feel we should keep them around just in case.  Please note there were a small number of documentation changes to address a mistake.
Resolves #4
=> Replace conda with pip

pavics-component/.gitignore, pavics-component/docker-compose-extra.yml, pavics-component/thunderbird-magpie-permission.cfg.template, pavics-component/thunderbird-magpie-provider.cfg.template, pavics-component/thunderbird_canarie_api_monitoring.py.template, pavics-component/wps.cfg.template
@nikola-rados This requires the PR https://github.com/bird-house/birdhouse-deploy/pull/36 on `birdhouse-deploy` repo.
@huard, @tlogan2000, FYI how a component can be hooked into our PAVICS stack without any code change. 
Assume `thunderbird` repo is checkout along-side with `birdhouse-deploy`
repo because we use `../../thunderbird/pavics-component` path for volume
mount.
`env.local` config to add to activate this component:
```
export EXTRA_CONF_DIRS="$EXTRA_CONF_DIRS /somepath/thunderbird/pavics-component"
export AUTODEPLOY_EXTRA_REPOS="$AUTODEPLOY_EXTRA_REPOS /somepath/thunderbird/pavics-component"
export THUNDERBIRD_IMAGE="tlvu/thunderbird:i3-gen-climos"
```
The bird will be accessible at
https://$PAVICS_FQDN/twitcher/ows/proxy/thunderbird/wps or
http://$PAVICS_FQDN:8099/wps.
Public …
=> Add pavics component config

.github/workflows/ci.yml, setup.py, test_requirements.txt, tests/common.py, tests/test_wps_update_metadata.py, thunderbird/processes/wps_generate_climos.py, thunderbird/processes/wps_update_metadata.py
This issue introduces a code quality check into the CI using `black` instead of `flake8`.
Resolves #27.
=> Formatting with black

notebooks/demo.ipynb, notebooks/demo_update_metadata.ipynb
This PR replaces the uses of `opendap` in the `demo.ipynb` and `demo_update_metadata.ipynb` notebooks with `netcdf` to be up to date with the refactoring.
=> Replace opendap variable with netcdf

tests/common.py, tests/test_wps_generate_climos.py
The opendap file in `common.py` has been changed to 
`http://docker-dev03.pcic.uvic.ca/twitcher/ows/proxy/thredds/dodsC/datasets/TestData/fdd_seasonal_CanESM2_rcp85_r1i1p1_1951-2100.nc` and the resolution in the online test where `dry_run = False` has been changed to `"all"` to fix the errors/warnings with these tests.
=> Fix errors in wps_generate_climos online tests

requirements.txt, tests/common.py, tests/test_wps_generate_climos.py, thunderbird/processes/wps_generate_climos.py
This PR closes #37 
`wps_generate_climos` has been modified to call `create_climo_files` function with one more argument `climo_period`. Furthermore, if `climo` option is not passed in as an input, it automatically sets `climo =  climo = standard_climo_periods().keys()` to maintain the `generate_climos` behaviors of `ce-dataprep`. Additionally, tests on local_nc files have been added to `test_wps_generate_climos`.
=> Issue/37 wps_generate_climos modified to adapt the version change in ce-dataprep

tests/common.py, tests/test_wps_generate_climos.py, tests/test_wps_generate_prsn.py, tests/test_wps_update_metadata.py
This PR "partially" resolves #40 
`run_wps_process()` function in each test files has been refactored into `common.py`. However, the format of parameters tuple could not be synchronized for every test files, thus each test files have their own `parameters()` function.
=> Synchronize run_wps_process throughout all the test files

requirements.txt
Much of the work to solve the issue was done behind the scenes.  New configuration settings for `ssl` verification, a new `cert` bundle and metadata updates to test files. The only change that was needed on the repo side was to include the newest version of `netCDF4`. This version matches the default version used in `birdhouse-deploy`'s `jupyter` container.  That way our CI/`pytest` tests will be on the same page as the "prod" env.
I encourage reviewers to visit the [jupyter hub](https://docker-dev03.pcic.uvic.ca) instance to test out `thunderbird`. Please notify me if there are any broken files that I missed. 
Resolves #41.
=> Solve netcdf inconsistency

setup.cfg
This PR resolves #34 
It looks like the pytest's default command line option `/tests` in `setup.cfg` restrained us to test on specific tests defined as `pytest tests/test_*.py`. Removing this [line](https://github.com/pacificclimate/thunderbird/compare/i34-define-specific-test#diff-380c6a8ebbbce17d55d50ef17d3cf906L31) should solve the problem. However, I wonder if there were any particular reasons that the option was included, so please let me know if it must be included. Following is an example pytest run on `tests/test_wps_update_metadata.py::test_wps_update_metadata_opendap`:
```
slim@devel2:~/Desktop/thunderbird$ pytest tests/test_wps_update_metadata.py::test_wps_update_metadata_opendap
============================================= test session starts …
```
=> Removed `/tests` from pytest command-line-options-defaults(addopts) to make specific test definition available.

tests/test_wps_generate_climos.py
This PR deals with [issue 67](https://github.com/pacificclimate/thunderbird/issues/67), which fixes the incomputable output resolution warnings in `test_wps_generate_climos.py`. A `build_resolutions` function has been added to allow for a list of resolutions to be used as input rather than just one string.
=> Change resolution parameters to fix warnings

Dockerfile
This resolves #79 by removing the package causing the problem.  I have tested a `thunderbird` instance running with this package removed and had no issues.
=> Remove OS package causing scan failure

requirements.txt, thunderbird/processes/wps_generate_climos.py
This PR closes #76 
`wps_genereate_climos` now uses the same strategy of `generate_climos` script of `ce-dataprep`.
`dry_run_handler` and `generate_climos` functions are imported from `dp` package and replace the functionally equivalent codes in `self._handler`.
There was an issue that the previous version of `ce-dataprep` did not pass `split_intervals` argument into `create_climo_files`. It has been resolved in the latest version 0.8.4 by implementing `generate_climos` function. Therefore, calling the function also resolves #68
For dry_run, logging messages of `dry_run_handler` are redirected to the output `.txt` file, and an example looks like below:
```
Dry Run
generate_climos:
INFO:dp.generate_climos:Processing: https://docker-dev03.pcic.uvic.ca/twitcher/ows/proxy/thredds/dodsC/dataset …
```
=> Utilize newly implemented functions in ce-dataprep

thunderbird/processes/wps_generate_climos.py, thunderbird/processes/wps_generate_prsn.py, thunderbird/utils.py
This PR closes #82 
`wps_generate_prsn`'s dry_run output strategy now follows `wps_generate_climos`. Since they are using a similar method, `dry_run_info` function is moved to `utils.py`.
=> generate_prsn's dry_run logging messages are redirected to dry.txt

tests/test_wps_generate_climos.py
This PR close #84 
After manually running `generate_climos` on every single `tiny` file, I have figured `gcm` data do not have standard climo periods, which makes them not adequate for `generate_climos` run. Also, some local `NetCDF` files do not have `7100` climo period, hence it is replaced by `6190`.
=> validate test_wps_generate_climos inputs

notebooks/demo_processes.ipynb, requirements.txt, thunderbird/processes/wps_decompose_flow_vectors.py, thunderbird/processes/wps_generate_climos.py, thunderbird/processes/wps_generate_prsn.py, thunderbird/processes/wps_split_merged_climos.py, thunderbird/processes/wps_update_metadata.py, thunderbird/utils.py
This PR solves [issue 90](https://github.com/pacificclimate/thunderbird/issues/90), which is to update each process to use the `log_handler` function from `wps-tools 0.1.2`. In doing so, a logger object has been created with a unique formatter.
=> Use updated log_handler and create thunderbird logger

.github/workflows/python-ci.yml, Makefile
- update `makefile`
- use `make` in `ci` action
The `makefile` fell a bit out of date with our changes. This PR updates some existing commands and adds new ones. Running `make` will take care of a full installation, while running `make develop` will runs further installs for development. `thunderbird` can also be started, stopped and restarted using `make`. However, we should steer clear from using these commands until the signal issue in `cdo` is solved.
Resolves #93
=> Makefile update

pavics-component/wps.cfg.template, thunderbird/default.cfg
Resolves #107.
```
[nrados@docker-dev03 birdhouse]$ docker logs thunderbird
[2020-09-29 19:23:44 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-09-29 19:23:44 +0000] [1] [INFO] Listening at: http://0.0.0.0:5001 (1)
[2020-09-29 19:23:44 +0000] [1] [INFO] Using worker: sync
[2020-09-29 19:23:44 +0000] [8] [INFO] Booting worker with pid: 8
2020-09-29 19:23:58 INFO: thunderbird: Request: getcapabilities
2020-09-29 19:23:58 INFO: thunderbird: Request: getcapabilities
2020-09-29 19:24:02 INFO: thunderbird: Request: getcapabilities
2020-09-29 19:24:02 INFO: thunderbird: Request: getcapabilities
```
=> Suppress sql logging with config

pavics-component/wps.cfg.template
Resolves #110 
The input file size limit can be configured as [maxrequestsize](https://pywps.readthedocs.io/en/latest/configuration.html#server) in `pywps` configuration file. The maximum limit to the input is now set to 100 GB based on the [largest files](https://docker-dev03.pcic.uvic.ca/twitcher/ows/proxy/thredds/catalog/datasets/BCCAQv2/catalog.html) in the server
=> Increase maxrequestsize to 100 GB

docs/source/notebooks/wps_update_metadata_demo.ipynb, tests/test_wps_update_metadata.py, thunderbird/default.cfg, thunderbird/processes/wps_update_metadata.py
- Add a ComplexInput `updates_file` in `wps_update_metadata`.
- Change the name of the LiteralInput `updates` to 'updates_string` in `wps_update_metadata`.
- Updated `test_wps_update_metadata` and `wps_update_metadata_demo` to test the changes.
- Increased `maxrequestsize` of Docker containers for development purpose.
Resolves #115 
The issue was caused due to the inability of uploading `yaml` files to Docker containers since the input was passed as a [literal input](https://pywps.readthedocs.io/en/latest/process.html#literaldata). The input is now replaced to a complex input with `supported_formats=[`[Format](https://pywps.readthedocs.io/en/latest/_modules/pywps/inout/formats.html#Format)`(mime_type="text/x-yaml", extension=".yaml",)]` since `yaml` is not in predefined …
=> ComplexInput allows Thunderbird to access local updates yaml files

thunderbird/processes/wps_update_metadata.py
resolves #123 
`.file` IOHandler is the primary use case for accessing `input.yaml` file if available. The cause of malfunctioning in uploading the local `updates_file` to Docker containers has not been identified yet.
=> Use _file attribute when available

Makefile, docs/source/notebooks/wps_decompose_flow_vectors_demo.ipynb, docs/source/notebooks/wps_generate_climos_demo.ipynb, docs/source/notebooks/wps_generate_prsn_demo.ipynb, docs/source/notebooks/wps_split_merged_climos_demo.ipynb, docs/source/notebooks/wps_update_metadata_demo.ipynb, thunderbird/utils.py
The goal was to create a way for us to test against dev versions of birds without having to manually change the notebooks. A command has been added to the `Makefile` that injects a user prompted input into the notebooks. The prompt is for the port portion of the `http://docker-dev03.pcic.uvic.ca:[port]/wps` url. Right now I have a dev instance of `thunderbird` running on `30666`, you can use that for testing this command. 
I added a function in the `utils` module that handles the logic for choosing the port. I plan to move this into `wps-tools` before bringing this change to other birds.
Resolves #122.
=> Custom demo ports

.github/workflows/python-ci.yml, requirements.txt, requirements_dev.txt, setup.py
This PR resolves #163. In doing so, `nbclient` has been pinned to `~0.5.10` to resolve the incompatibility with `pytest-notebook`, `jinja2` has an upper bound of `<3.1.0` to fix the `ImportError` when running automated tests, and support for Python 3.6 has dropped. Additionally, `ce-dataprep` has been updated to the latest version.
=> I163 resolve dependencies
